services:
  Ensepar\Html2pdfBundle\Factory\Html2pdfFactory:
    class: Ensepar\Html2pdfBundle\Factory\Html2pdfFactory
    arguments:
      - '%html2pdf.orientation%'
      - '%html2pdf.format%'
      - '%html2pdf.lang%'
      - '%html2pdf.unicode%'
      - '%html2pdf.encoding%'
      - '%html2pdf.margin%'

  html2pdf_factory:
    alias: Ensepar\Html2pdfBundle\Factory\Html2pdfFactory
    public: true
